name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write # 👈 Needed for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Build client
        run: npm run build
        working-directory: ./client
        env:
          CI: false
          MONGODB_URI: ${{ vars.MONGODB_URI }}
          PORT: ${{ vars.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
